### ISSUE TITLE
'material' always returns 'keine' although Equipment is required

### ISSUE THREAD

**Issue by polarbearing** [BjoernLudwig/pyacb2pdf#12]
Table entry 'Voraussetzungen / b)' is always 'keine' although Equipment is required.

A reason could be that in ```input/kursdaten_prop.properties``` and ```Core/Parser.py``` you process ```Ausrüstung``` while the correct XML entry is ```Ausruestung```.

Other entries with expanded Umlauts are: Stuetzpunktinfo, Aenderungsdatum, FreiePlaetze, apparently not used currently. 
The XML never had Umlauts here, until Nov 12 it had underscores in these positions. 

Please note that equipment lists can be quite long, so they would dramatically increase you cell sizes.

BTW it took me some time to understand that 'prerequisites' is parsed from 4 XML fields ```Voraussetzung, Ausrüstung, Kurskosten, Leistungen```, while their meaning is then determined by their position in the function as ```(personal, material, financial, offers)```.

**Comment by BjoernLudwig** [comment]
The origin of the mistake is correctly identified and the anticipated result of the correction as well. So the solution for now will be to leave out equipment prerequisites for now and [find a better layout](https://github.com/BjoernLudwigPTB/XMLToPDFConverter/projects/1#card-15177374.)
